CREATE TABLE `gate` (
  `id_gate` INT(11) NOT NULL AUTO_INCREMENT,
  `nama_gate` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`id_gate`)
) ENGINE=INNODB AUTO_INCREMENT=18 DEFAULT CHARSET=latin1

CREATE TABLE `log` (
  `id_log` INT(11) NOT NULL AUTO_INCREMENT,
  `id_gate_log` INT(11) DEFAULT NULL,
  `nrp_log` VARCHAR(50) DEFAULT NULL,
  `message` VARCHAR(255) NOT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_log`)
) ENGINE=INNODB AUTO_INCREMENT=37 DEFAULT CHARSET=latin1

CREATE TABLE `user` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `nrp` VARCHAR(50) NOT NULL,
  `nama` VARCHAR(255) NOT NULL,
  `role` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_user`,`nrp`)
) ENGINE=INNODB AUTO_INCREMENT=22 DEFAULT CHARSET=latin1
